"""Generated synthetic CPU protocol fixtures; no target/GPU evidence is mocked.

The fake digest/reference strings below test rejection/accounting only. Neither
passing these tests nor accepting their record structure qualifies device math.
"""

import copy
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from megartx import prefill_plan as p
from megartx import prefill_runner as r


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs/prefill"
DIGEST = "a" * 64


def inputs(filled=False):
    manifest = p.read_json(DOCS / "runner-plan-native.json")
    plan = p.read_json(DOCS / "profile-plan-native.json")
    prompts = {"schema": "megartx-prefill-private-prompts-v1",
               "token_ids": {"p2048": [i % 262144 for i in range(2048)]}}
    if filled:
        manifest["run_namespace"] = "synthetic-test"
        manifest["launcher"].update(pr15_final_commit="b" * 40,
                                    source_manifest_sha256=DIGEST,
                                    stream_provider_sha256=DIGEST,
                                    supported_chunk_tokens=[255, 256, 512, 1024, 2048, 8192])
        manifest["observer_sites"] = {key: DIGEST for key in r.PROFILE_COMPONENTS}
        manifest["cache_layout"] = {"local_storage_policy": "full_context", "page_tokens": 16, "layout_sha256": DIGEST}
        for key in plan["freeze"]:
            plan["freeze"][key] = (DIGEST if key.endswith("_sha256") else
                                     "b" * 40 if key.endswith("_commit") else "synthetic-not-approval")
        plan["freeze"].update(sampling_policy="greedy_seed_1234", eos_policy="ignore_eos_256")
        plan["resource_bounds"] = {key: 2**40 for key in p.RESOURCE_KEYS}
        plan["resource_bounds"].update(max_gpu_jobs=1, max_requests=100,
                                         memory_reserve_bytes=2**30, max_extra_scratch_bytes=2**20)
        plan["workloads"][0]["prompt_token_ids_sha256"] = r.digest(prompts["token_ids"]["p2048"])
    return manifest, plan, prompts


def synthetic_stream(job, response_id, first_ns):
    token = {"id": response_id, "choices": [{"index": 0, "token_ids": [17] * 256,
                                              "finish_reason": "length"}], "usage": None}
    usage = {"id": response_id, "choices": [], "usage": {"prompt_tokens": job["prompt_tokens"],
             "completion_tokens": 256, "total_tokens": job["prompt_tokens"] + 256}}
    return [{"received_ns": first_ns, "data": json.dumps(token)},
            {"received_ns": first_ns + 1, "data": json.dumps(usage)},
            {"received_ns": first_ns + 2, "data": "[DONE]"}]


def synthetic_records(protocol, prompts):
    records = {"schema": "megartx-prefill-records-v1", "scope_sha256": protocol["scope_sha256"],
               "provenance": {"kind": "synthetic_cpu", "origin_reference": "generated by test_prefill_runner.py",
                              "artifact_sha256": DIGEST, "sanitized": True},
               "host_clock_id": "synthetic-single-clock", "runs": []}
    for run_index, job in enumerate(protocol["jobs"]):
        begin = run_index * 10000
        record = {key: job[key] for key in ("run_id", "request_id", "mode", "region", "state", "observer_enabled")}
        record.update(status="complete", stop_reason=None, checks=None,
                      lifecycle_receipts={"startup_sha256": DIGEST, "cleanup_sha256": DIGEST,
                        "launcher_source_manifest_sha256": protocol["launcher"]["source_manifest_sha256"],
                        "ownership_scope_sha256": protocol["scope_sha256"], "owned_only": True, "cleanup_complete": True},
                      run_begin_ns=begin, run_end_ns=begin + 9000, trace_bytes=0,
                      initialization=None, forwards=[], handoff=None,
                      server_response_id=None, client_events=[], timing=None, profile=None, memory=None)
        if job["mode"] == "initialization":
            record["initialization"] = {k: 10 for k in ("load_ns", "import_repack_ns", "compile_ns",
                                                       "allocation_ns", "warmup_ns", "build_rss_peak_bytes", "build_wall_ns")}
        else:
            for index, (start, end) in enumerate(job["spans"]):
                record["forwards"].append({"forward_index": index, "start": start, "end": end,
                                           "rows": end - start, "output_rows": 0, "layer_count": 30,
                                           "token_ids_sha256": r.digest(prompts["token_ids"][job["workload"]][start:end]),
                                           "complete": True})
            record["handoff"] = {"complete": True, "poisoned": False,
                "committed_length": job["prompt_tokens"], "next_position": job["prompt_tokens"],
                "capacity": job["capacity_tokens"], "kv_dtype": "bfloat16",
                "comparison_receipt_sha256": DIGEST, "layers": [{"layer": layer,
                    "kind": "global" if layer in r.GLOBAL_LAYERS else "local",
                    "positions_start": 0 if layer in r.GLOBAL_LAYERS else job["prompt_tokens"] - 1024,
                    "positions_end": job["prompt_tokens"], "processed_k_sha256": DIGEST,
                    "processed_v_sha256": DIGEST, "layout_sha256": DIGEST} for layer in range(30)]}
            record["server_response_id"] = "synthetic-response-" + job["request_id"]
            record["client_events"] = synthetic_stream(job, record["server_response_id"], begin + 8000)
        if job["mode"] == "correctness":
            record["checks"] = {"oracle_contract_sha256": protocol["identities"]["oracle_contract_sha256"],
                                "decode_control_commit": protocol["identities"]["decode_control_commit"],
                                "finite_intermediates": True, "natural_routing": True,
                                "cache_oracle_match": True, "logit_oracle_match": True,
                                "comparison_receipt_sha256": DIGEST}
        if job["mode"] == "timing":
            record["timing"] = {"request_accept_ns": begin + 100, "input_ready_ns": begin + 200,
                                "prompt_begin_ns": begin + 1000, "prompt_complete_ns": begin + 5000,
                                "kv_ready_ns": begin + 6000, "first_token_ns": begin + 8000,
                                "prompt_tokens": job["prompt_tokens"],
                                "chunk_rows": [end - start for start, end in job["spans"]],
                                "state": job["state"], "observer_enabled": False,
                                "preallocated": job["state"] == "warm", "bucket_warmed": job["state"] == "warm"}
        if job["mode"] == "profile":
            record["trace_bytes"] = 10
            profile = {"stream_bindings": [{"runtime_stream_key": "runtime-object-0", "cupti_stream_id": 29,
                                            "provider_sha256": protocol["launcher"]["stream_provider_sha256"]}],
                       "launches": [], "kernels": [], "expert_rows": []}
            pairs = ([(len(job["spans"]) - 1, 29)] if job["region"] == "head" else
                     [(i, layer) for i in range(len(job["spans"])) for layer in range(30)])
            component = {"attention": "attention", "dense": "qkv", "expert": "expert_fc1", "head": "head"}[job["region"]]
            for index, (forward, layer) in enumerate(pairs):
                m = job["spans"][forward][1] - job["spans"][forward][0]
                correlation = str(index)
                profile["launches"].append({"correlation_id": correlation, "forward_index": forward,
                    "layer": layer, "component": component, "source_site": "synthetic-source-site",
                    "source_sha256": protocol["observer_sites"][job["region"]],
                    "runtime_stream_key": "runtime-object-0", "m": 1 if job["region"] == "head" else m, "n": 2816, "k": 2816})
                profile["kernels"].append({"kernel_id": correlation, "correlation_id": correlation,
                    "cupti_stream_id": 29, "name": "synthetic-kernel", "device_begin_ns": index * 10,
                    "device_end_ns": index * 10 + 20, "bytes": 12, "grid": [1, 1, 1], "block": [32, 1, 1]})
                if job["region"] == "expert":
                    profile["expert_rows"].append({"forward_index": forward, "layer": layer,
                        "selected_m": [m] * 8 + [0] * 120, "positive_m": [m] * 8 + [0] * 120,
                        "scheduled_m": [m] * 8 + [0] * 120, "route_sha256": DIGEST,
                        "correction_hits": 0, "suppressed_stock_rows": 0})
            record["profile"] = profile
        if job["mode"] == "memory":
            local = (job["capacity_tokens"] if protocol["cache_layout"]["local_storage_policy"] == "full_context" else
                     max(1024, max(end - max(0, start - 1023) for start, end in job["spans"])))
            page = protocol["cache_layout"]["page_tokens"]
            local = (local + page - 1) // page * page
            global_positions = (job["capacity_tokens"] + page - 1) // page * page
            allocations = [{"allocation_id": category, "category": category, "bytes": size}
                           for category, size in {"model_scales": 4096, "kv_local": 25 * 8192 * local,
                                                  "kv_global": 5 * 4096 * global_positions, "scratch": 1024}.items()]
            size = sum(a["bytes"] for a in allocations)
            record["memory"] = {"device_total_bytes": 2**35, "samples": [{"phase": phase,
                "allocated_bytes": size, "reserved_bytes": size + 4096, "device_used_bytes": size + 8192,
                "allocations": copy.deepcopy(allocations)} for phase in
                ["load", "import_repack", "compile_warmup", *[f"chunk_{i}" for i in range(len(job["spans"]))],
                 "handoff", "first_head", "decode_continuation"]]}
        records["runs"].append(record)
    return records


class ProtocolTests(unittest.TestCase):
    def test_merged_binding_preserves_reviewed_plan_and_historical_sources(self):
        manifest, plan = r.load_inputs(DOCS / "runner-plan-native.json", DOCS / "profile-plan-native.json",
            DOCS / "source-binding-native.json", DOCS / "runner-binding-native.json", ROOT)
        # PR19's entire plan, except PR15's reviewed source-manifest pointer.
        semantic_plan = copy.deepcopy(plan)
        semantic_plan["binding"].pop("source_manifest_sha256")
        self.assertEqual(r.digest(semantic_plan),
                         "a3819e2816aa7f3292d216bdcef56e7fe3af3539ba1bacb6604c74e0c4b58196")
        source = p.read_json(DOCS / "source-binding-native.json")
        self.assertEqual(plan["binding"]["source_manifest_sha256"],
                         hashlib.sha256((DOCS / "source-binding-native.json").read_bytes()).hexdigest())
        self.assertEqual(len(source["repo_files"]), 12)
        self.assertEqual(r.digest(source["repo_files"]),
                         "05f0b4f7f009024b082e170539217fe5839da5f86d6eb7e88105832feea2fc66")
        self.assertEqual(len(source["reviewed_source_overlays"]), 2)
        overlay = source["reviewed_source_overlays"][0]
        self.assertEqual(overlay["source_head"], "dfd77d8c80d333fc9531955795476f7e9c0cbab2")
        self.assertEqual(overlay["review_scope"], "cpu_source_compatibility_only")
        historical_review = p.read_json(DOCS / "pr15-source-reconciliation.json")
        for name, expected in overlay["repo_files"].items():
            self.assertEqual(historical_review["files"][name]["candidate_sha256"], expected)
        self.assertEqual(hashlib.sha256((DOCS / "pr15-source-reconciliation.json").read_bytes()).hexdigest(),
                         source["source_review_sha256"])
        attribution = p.read_json(DOCS / "decode-attribution-source-reconciliation.json")
        self.assertEqual(hashlib.sha256((DOCS / "decode-attribution-source-reconciliation.json").read_bytes()).hexdigest(),
                         source["attribution_review_sha256"])
        current = source["reviewed_source_overlays"][1]
        self.assertEqual(current["source_head"], attribution["source_head"])
        self.assertEqual(current["review_scope"], "cpu_source_compatibility_only")
        for name, expected in current["repo_files"].items():
            self.assertEqual(hashlib.sha256((ROOT / name).read_bytes()).hexdigest(), source["native_source_overlay"]["repo_files"][name])
            self.assertEqual(attribution["files"][name]["candidate_sha256"], expected)
        self.assertEqual(manifest["repository_base_commit"], "5a32504b5ccb209a779b8a110eb2ebc56d72e373")
        self.assertEqual(hashlib.sha256((ROOT / "src/megartx/prefill_runner.py").read_bytes()).hexdigest(),
                         "851424938375fd5b4e77930fa0c8f4f88e88532b050f25e9052b0ed838525d93")
        protocol = r.compile_protocol(manifest, plan)
        self.assertFalse(protocol["gpu_execution_available"])
        self.assertFalse(protocol["gpu_qualified"])
        self.assertFalse(protocol["prerequisites_complete"])

    def test_unknown_plan_and_manifest_bytes_still_reject(self):
        with tempfile.TemporaryDirectory() as directory:
            directory = Path(directory)
            paths = [directory / name for name in
                     ("runner-plan-native.json", "profile-plan-native.json", "source-binding-native.json", "runner-binding-native.json")]
            for path in paths:
                shutil.copyfile(DOCS / path.name, path)
            r.load_inputs(*paths, ROOT)
            original = paths[1].read_bytes()
            altered = p.read_json(paths[1])
            altered["workloads"][0]["chunk_tokens"] = [256, 2048]
            for content in (original + b"\n", json.dumps(altered).encode()):
                paths[1].write_bytes(content)
                with self.assertRaisesRegex(ValueError, "Prefill plan digest changed"):
                    r.load_inputs(*paths, ROOT)
            paths[1].write_bytes(original)
            for path, error in ((paths[2], "Source manifest digest changed"),
                                (paths[3], "Runner binding digest changed")):
                content = path.read_bytes()
                path.write_bytes(content + b"\n")
                with self.assertRaisesRegex(ValueError, error):
                    r.load_inputs(*paths, ROOT)
                path.write_bytes(content)
            # Even a deliberately repinned private plan retains strict semantics.
            for field, value, error in (("unknown", True, "plan: missing or unsupported fields"),
                                        ("gpu_enabled", True, "gpu_enabled: unsupported contract")):
                altered = json.loads(original)
                altered[field] = value
                paths[1].write_text(json.dumps(altered))
                manifest = p.read_json(paths[0])
                manifest["plan_sha256"] = hashlib.sha256(paths[1].read_bytes()).hexdigest()
                paths[0].write_text(json.dumps(manifest))
                with self.assertRaisesRegex(ValueError, error):
                    r.load_inputs(*paths, ROOT)

    def test_checked_in_inputs_bind_and_remain_disabled(self):
        manifest, plan = r.load_inputs(DOCS / "runner-plan-native.json", DOCS / "profile-plan-native.json",
            DOCS / "source-binding-native.json", DOCS / "runner-binding-native.json", ROOT)
        protocol = r.compile_protocol(manifest, plan)
        self.assertEqual((len(protocol["jobs"]), protocol["request_count"]), (99, 88))
        self.assertFalse(protocol["prerequisites_complete"])
        self.assertFalse(protocol["gpu_execution_available"])
        for name in ("receipt.numerical", "receipt.ownership", "receipt.resource", "launcher.pr15_final_commit"):
            self.assertIn(name, protocol["blockers"])
        self.assertEqual({j["prompt_tokens"] for j in protocol["jobs"]}, {2048, 8192})
        for job in protocol["jobs"]:
            self.assertEqual(job["capacity_tokens"], job["prompt_tokens"] + 256)
            self.assertEqual(sum(end - start for start, end in job["spans"]), job["prompt_tokens"])
        self.assertEqual(next(j for j in protocol["jobs"] if j["chunk_tokens"] == 255)["spans"][-1], [2040, 2048])

    def test_supported_chunks_and_separate_run_ids(self):
        manifest, plan, _ = inputs(True)
        manifest["launcher"]["supported_chunk_tokens"] = [256]
        protocol = r.compile_protocol(manifest, plan, "p2048", 255)
        self.assertIn("p2048: launcher/collector chunk 255 unsupported", protocol["blockers"])
        self.assertEqual(len({j["run_id"] for j in protocol["jobs"]}), 9)
        self.assertEqual([j["region"] for j in protocol["jobs"] if j["mode"] == "profile"],
                         ["attention", "dense", "expert", "head"])
        for workload, chunk in [("p32768", 32768), ("dspark", 8), ("p2048", 1), (None, 256)]:
            with self.subTest(workload=workload, chunk=chunk), self.assertRaises(ValueError):
                r.compile_protocol(manifest, plan, workload, chunk)

    def test_receipts_are_content_bound_scoped_and_nonrecursive(self):
        manifest, plan, _ = inputs(True)
        with tempfile.TemporaryDirectory() as directory:
            scope = r.compile_protocol(manifest, plan, "p2048", 1024)["scope_sha256"]
            evidence_data = json.dumps({"provenance": "synthetic CPU test artifact; no target evidence"}).encode()
            evidence_hash = hashlib.sha256(evidence_data).hexdigest()
            evidence_path = Path(directory) / (evidence_hash + ".evidence.json")
            evidence_path.write_bytes(evidence_data)
            for kind in r.RECEIPTS - {"fit_p8192"}:
                receipt = {"schema": "megartx-prefill-receipt-v1", "kind": kind, "scope_sha256": scope,
                           "decision": "accepted", "evidence_sha256": evidence_hash,
                           "reviewer_reference": "synthetic format test, not an approval"}
                data = (json.dumps(receipt) + "\n").encode()
                receipt_hash = hashlib.sha256(data).hexdigest()
                (Path(directory) / (receipt_hash + ".json")).write_bytes(data)
                manifest["receipts"][kind] = receipt_hash
            plan["workloads"][0]["fit_receipt_sha256"] = manifest["receipts"]["fit_p2048"]
            protocol = r.compile_protocol(manifest, plan, "p2048", 1024, directory)
            self.assertEqual(protocol["scope_sha256"], scope)
            self.assertTrue(protocol["prerequisites_complete"])
            with self.assertRaisesRegex(ValueError, "GPU execution disabled"):
                r.require_live_execution(protocol)
            evidence_path.unlink()
            self.assertFalse(r.compile_protocol(manifest, plan, "p2048", 1024, directory)["prerequisites_complete"])
            evidence_path.write_bytes(evidence_data + b" ")
            with self.assertRaisesRegex(ValueError, "evidence digest changed"):
                r.compile_protocol(manifest, plan, "p2048", 1024, directory)
            evidence_path.write_bytes(evidence_data)
            changed = copy.deepcopy(plan)
            changed["resource_bounds"]["memory_reserve_bytes"] += 1
            with self.assertRaisesRegex(ValueError, "receipt scope"):
                r.compile_protocol(manifest, changed, "p2048", 1024, directory)
            path = Path(directory) / (manifest["receipts"]["ownership"] + ".json")
            path.write_text(path.read_text() + " ")
            with self.assertRaisesRegex(ValueError, "Receipt digest changed"):
                r.compile_protocol(manifest, plan, "p2048", 1024, directory)
            path.unlink()
            self.assertFalse(r.compile_protocol(manifest, plan, "p2048", 1024, directory)["prerequisites_complete"])

    def test_unknown_fields_wrong_types_lanes_and_ambiguous_output_rejected(self):
        manifest, plan, _ = inputs(True)
        changes = [lambda m: m.update(gpu_enabled=True), lambda m: m.update(extra=True),
                   lambda m: m["launcher"].update(pr15_final_commit="main"),
                   lambda m: m["launcher"].update(supported_chunk_tokens=[True]),
                   lambda m: m.update(run_namespace="../escape")]
        for change in changes:
            altered = copy.deepcopy(manifest)
            change(altered)
            with self.assertRaises(ValueError):
                r.validate_manifest(altered)
        for change in [lambda p: p["controls"].update(kv_dtype="fp8"),
                       lambda p: p["freeze"].update(eos_policy="natural_eos"),
                       lambda p: p["freeze"].update(sampling_policy="unspecified")]:
            altered = copy.deepcopy(plan)
            change(altered)
            with self.assertRaises(ValueError):
                r.compile_protocol(manifest, altered)
        plan["resource_bounds"]["max_requests"] = 7
        self.assertIn("max_requests: serialized suite exceeds bound", r.compile_protocol(manifest, plan, "p2048", 2048)["blockers"])

    def test_payload_has_exact_prompt_usage_and_unchanged_controls(self):
        manifest, plan, prompts = inputs(True)
        protocol = r.compile_protocol(manifest, plan, "p2048", 255)
        job = protocol["jobs"][1]
        payload = r.request_payload(job, prompts["token_ids"]["p2048"])
        self.assertEqual(payload["max_tokens"], 256)
        self.assertFalse(payload["add_special_tokens"])
        self.assertTrue(payload["ignore_eos"])
        self.assertNotIn("allowed_token_ids", payload)
        self.assertEqual(payload["request_id"], job["request_id"])
        with self.assertRaises(ValueError):
            r.request_payload(job, list(reversed(payload["prompt"])))
        with self.assertRaises(ValueError):
            r.request_payload(protocol["jobs"][0], payload["prompt"])

    def test_cli_bindings_disabled_execution_exclusive_output_and_no_gpu_import(self):
        args = ["--manifest", str(DOCS / "runner-plan-native.json"), "--plan", str(DOCS / "profile-plan-native.json"),
                "--source-manifest", str(DOCS / "source-binding-native.json"), "--runner-binding", str(DOCS / "runner-binding-native.json"),
                "--root", str(ROOT), "--workload", "p2048", "--chunk", "2048"]
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory) / "protocol.json"
            process = subprocess.run([sys.executable, "-m", "megartx.prefill_runner", *args, "--output", str(output)],
                                     cwd=ROOT, capture_output=True, text=True, timeout=10)
            self.assertEqual(process.returncode, 0, process.stderr)
            self.assertEqual(json.loads(output.read_text())["request_count"], 8)
            for extra in (["--execute-gpu"], ["--output", str(output)], ["--workload", "p32768"]):
                process = subprocess.run([sys.executable, "-m", "megartx.prefill_runner", *args, *extra],
                                         cwd=ROOT, capture_output=True, text=True, timeout=10)
                self.assertEqual(process.returncode, 2)
        code = "import sys; from megartx import prefill_runner; assert not any(n.split('.')[0] in {'torch','triton','vllm','flashinfer','numpy','requests'} for n in sys.modules); assert 'megartx.vllm_scale_plugin' not in sys.modules"
        process = subprocess.run([sys.executable, "-c", code], cwd=ROOT, capture_output=True, text=True, timeout=10)
        self.assertEqual(process.returncode, 0, process.stderr)

    def test_extended_source_binding_drift_inventory_and_symlinks(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source = p.read_json(DOCS / "source-binding-native.json")
            for name in set(source["repo_files"]) | r.RUNNER_FILES | {"scripts/run_scale_validation.py", "docs/prefill/native-source-reconciliation.json",
                    "docs/prefill/runner-plan-native.json", "docs/prefill/profile-plan-native.json",
                    "docs/prefill/source-binding-native.json", "docs/prefill/runner-binding-native.json"}:
                dest = root / name
                dest.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(ROOT / name, dest)
            paths = [root / "docs/prefill" / name for name in
                     ("runner-plan-native.json", "profile-plan-native.json", "source-binding-native.json", "runner-binding-native.json")]
            r.load_inputs(*paths, root)
            for name, error in (("docs/prefill/README.md", "Runner source drift"),
                                ("src/megartx/prefill_plan.py", "Runner source drift"),
                                ("numerical_reference/prefill_cache_reference.py", "Runner source drift"),
                                ("src/megartx/nvfp4_runtime.py", "Source drift"),
                                ("src/megartx/m1_live.py", "Source drift"),
                                ("src/megartx/vllm_scale_plugin.py", "Source drift")):
                with self.subTest(source=name):
                    file = root / name
                    original = file.read_bytes()
                    file.write_bytes(original + b"\n# unknown integration drift\n")
                    with self.assertRaisesRegex(ValueError, error):
                        r.load_inputs(*paths, root)
                    file.write_bytes(original)
            file = root / "src/megartx/prefill_runner.py"
            original = file.read_bytes()
            file.write_bytes(original + b"\n# drift\n")
            with self.assertRaisesRegex(ValueError, "Runner source drift"):
                r.load_inputs(*paths, root)
            file.write_bytes(original)
            file.unlink()
            file.symlink_to(ROOT / "src/megartx/prefill_runner.py")
            with self.assertRaisesRegex(ValueError, "symlinks"):
                r.load_inputs(*paths, root)
            binding = p.read_json(paths[-1])
            binding["repo_files"].pop("tests/test_prefill_runner.py")
            paths[-1].write_text(json.dumps(binding))
            manifest = p.read_json(paths[0])
            manifest["runner_binding_sha256"] = hashlib.sha256(paths[-1].read_bytes()).hexdigest()
            paths[0].write_text(json.dumps(manifest))
            with self.assertRaisesRegex(ValueError, "source inventory"):
                r.load_inputs(*paths, root)


class RecordTests(unittest.TestCase):
    def setUp(self):
        manifest, plan, self.prompts = inputs(True)
        self.protocol = r.compile_protocol(manifest, plan, "p2048", 255)
        self.records = synthetic_records(self.protocol, self.prompts)

    def run_for(self, mode, region=None, state=None):
        return next(x for x in self.records["runs"] if x["mode"] == mode and
                    (region is None or x["region"] == region) and (state is None or x["state"] == state))

    def check(self):
        return r.validate_records(self.protocol, self.records, self.prompts)

    def test_valid_synthetic_records_are_accounting_only(self):
        result = self.check()
        self.assertEqual((result["run_count"], result["request_count"]), (9, 8))
        self.assertEqual(result["provenance_kind"], "synthetic_cpu")
        for key in ("gpu_qualified", "numerical_qualified", "performance_qualified", "gpu_execution_available"):
            self.assertFalse(result[key])
        self.assertTrue(result["admission_blockers"])
        timing = next(x["timing"] for x in result["runs"] if x["mode"] == "timing" and x["state"] == "warm")
        self.assertEqual((timing["prompt_latency_ns"], timing["ttft_ns"], timing["handoff_ns"]), (4000, 7900, 1000))
        profile = next(x["profile"] for x in result["runs"] if x["mode"] == "profile")
        self.assertIsNone(profile["critical_path_ns"])
        self.assertGreater(sum(profile["kernel_sum_ns_by_component"].values()), sum(profile["stream_busy_union_ns"].values()))

    def test_forward_cache_correctness_and_partial_state_fail_closed(self):
        changes = [lambda x: x["forwards"].pop(), lambda x: x["forwards"][0].update(start=1),
                   lambda x: x["forwards"][0].update(rows=True), lambda x: x["forwards"][0].update(output_rows=1),
                   lambda x: x["forwards"][0].update(token_ids_sha256="f" * 64),
                   lambda x: x["handoff"].update(poisoned=True), lambda x: x["handoff"].update(capacity=2048),
                   lambda x: x["handoff"]["layers"].pop(), lambda x: x["handoff"]["layers"][0].update(positions_start=0),
                   lambda x: x["checks"].update(finite_intermediates=False),
                   lambda x: x["checks"].update(cache_oracle_match=False), lambda x: x.update(stop_reason="oracle_failure")]
        original = copy.deepcopy(self.records)
        for change in changes:
            self.records = copy.deepcopy(original)
            change(self.run_for("correctness"))
            with self.assertRaises(ValueError):
                self.check()

    def test_stream_usage_count_identity_clock_and_completion_errors(self):
        job = self.protocol["jobs"][1]
        for mutation in (lambda e: e.pop(), lambda e: e.append(copy.deepcopy(e[0])),
                         lambda e: e[1].update(received_ns=0),
                         lambda e: e[0].update(data='{"id":"other","choices":[]}'),
                         lambda e: e[1].update(data='{"id":"response","choices":[],"usage":{"prompt_tokens":2048,"completion_tokens":true,"total_tokens":2304}}'),
                         lambda e: e[0].update(data='{"id":"response","id":"response","choices":[]}')):
            events = synthetic_stream(job, "response", 100)
            mutation(events)
            with self.assertRaises(ValueError):
                r.parse_client_stream(events, job, "response")
        events = synthetic_stream(job, "response", 100)
        result = r.parse_client_stream(events, job, "response")
        self.assertTrue(result["multi_token_chunks"])
        self.assertFalse(result["itl_per_token_available"])

    def test_profile_source_counts_and_stream_correlation_failures(self):
        changes = [lambda x: x["kernels"][0].update(cupti_stream_id=1),
                   lambda x: x["kernels"][0].update(correlation_id="missing"),
                   lambda x: x["kernels"].append(copy.deepcopy(x["kernels"][0])),
                   lambda x: x["launches"][0].update(component="head"),
                   lambda x: x["launches"][0].update(source_sha256="f" * 64),
                   lambda x: x["launches"].pop(),
                   lambda x: x["expert_rows"][0]["selected_m"].__setitem__(0, 1),
                   lambda x: x["expert_rows"][0]["positive_m"].__setitem__(0, 1000),
                   lambda x: x["expert_rows"].pop()]
        original = copy.deepcopy(self.records)
        for change in changes:
            self.records = copy.deepcopy(original)
            change(self.run_for("profile", "expert")["profile"])
            with self.assertRaises(ValueError):
                self.check()

    def test_per_expert_selected_bound_preserves_total_and_allows_padding(self):
        original = copy.deepcopy(self.records)
        for row_index, m in ((0, 255), (-1, 8)):
            for variant in ("one_excess", "all_slots_one_expert"):
                with self.subTest(m=m, variant=variant):
                    self.records = copy.deepcopy(original)
                    row = self.run_for("profile", "expert")["profile"]["expert_rows"][row_index]
                    spans = self.protocol["jobs"][1]["spans"]
                    start, end = spans[row["forward_index"]]
                    self.assertEqual(end - start, m)
                    counts = ([m + 1, m - 1] + [m] * 6 + [0] * 120 if variant == "one_excess"
                              else [m * 8] + [0] * 127)
                    self.assertEqual(sum(counts), m * 8)
                    for field in ("selected_m", "positive_m", "scheduled_m"):
                        row[field] = counts.copy()
                    with self.assertRaisesRegex(ValueError, "selected_m"):
                        self.check()
            self.records = copy.deepcopy(original)
            row = self.run_for("profile", "expert")["profile"]["expert_rows"][row_index]
            self.assertEqual(max(row["selected_m"]), m)
            row["scheduled_m"][0] = m + 127
            self.assertTrue(self.check()["records_consistent"])

    def test_build_wall_cannot_exceed_initialization_interval(self):
        record = self.run_for("initialization")
        duration = record["run_end_ns"] - record["run_begin_ns"]
        # This stays within the independently frozen build bound, isolating the
        # lifecycle consistency check from the existing resource-limit check.
        self.assertLess(duration + 1, self.protocol["resource_bounds"]["max_build_seconds"] * 10**9)
        record["initialization"]["build_wall_ns"] = duration + 1
        with self.assertRaisesRegex(ValueError, "Build wall time exceeds initialization"):
            self.check()
        record["initialization"]["build_wall_ns"] = duration
        self.assertTrue(self.check()["records_consistent"])

    def test_tokenless_stream_event_cannot_precede_request_acceptance(self):
        for state in ("cold", "warm"):
            record = self.run_for("timing", state=state)
            acceptance = record["timing"]["request_accept_ns"]
            event = {"received_ns": acceptance - 1, "data": json.dumps({
                "id": record["server_response_id"], "choices": [], "usage": None})}
            self.assertGreaterEqual(event["received_ns"], record["run_begin_ns"])
            record["client_events"].insert(0, event)
            with self.subTest(state=state), self.assertRaisesRegex(ValueError, "precedes request acceptance"):
                self.check()
            event["received_ns"] = acceptance
            self.assertTrue(self.check()["records_consistent"])

    def test_memory_capacity_alias_reserve_scratch_phase_and_bounds(self):
        changes = [lambda m: m["samples"].pop(),
                   lambda m: m["samples"][3]["allocations"][1].update(bytes=1),
                   lambda m: m["samples"][3]["allocations"][2].update(bytes=1),
                   lambda m: m["samples"][0]["allocations"].append(copy.deepcopy(m["samples"][0]["allocations"][0])),
                   lambda m: m["samples"][0].update(device_used_bytes=m["device_total_bytes"]),
                   lambda m: m["samples"][0]["allocations"][-1].update(bytes=2**21),
                   lambda m: m["samples"][0].update(reserved_bytes=0),
                   lambda m: m["samples"][0].update(phase="chunk_0")]
        original = copy.deepcopy(self.records)
        for change in changes:
            self.records = copy.deepcopy(original)
            change(self.run_for("memory")["memory"])
            with self.assertRaises(ValueError):
                self.check()

    def test_suite_lifecycle_and_timing_instrumentation_errors(self):
        changes = [lambda xs: xs.pop(), lambda xs: xs.reverse(),
                   lambda xs: xs[1].update(run_begin_ns=0),
                   lambda xs: xs[0]["initialization"].update(build_rss_peak_bytes=2**41),
                   lambda xs: xs[0].update(initialization=None),
                   lambda xs: xs[0]["lifecycle_receipts"].update(cleanup_complete=False),
                   lambda xs: xs[0]["lifecycle_receipts"].update(launcher_source_manifest_sha256="f" * 64),
                   lambda xs: xs[-1].update(trace_bytes=1),
                   lambda xs: xs[-1]["timing"].update(observer_enabled=True),
                   lambda xs: xs[-1]["timing"].update(bucket_warmed=False),
                   lambda xs: xs[-1]["timing"].update(first_token_ns=1),
                   lambda xs: xs[1].update(timing=copy.deepcopy(xs[-1]["timing"]))]
        original = copy.deepcopy(self.records)
        for change in changes:
            self.records = copy.deepcopy(original)
            change(self.records["runs"])
            with self.assertRaises(ValueError):
                self.check()
        self.records = original
        for bound, limit in [("max_trace_bytes", 1), ("max_requests", 1), ("max_wall_seconds", 0)]:
            protocol = copy.deepcopy(self.protocol)
            protocol["resource_bounds"][bound] = limit
            with self.assertRaises(ValueError):
                r.validate_records(protocol, self.records, self.prompts)

    def test_record_file_duplicate_nonfinite_size_and_symlink(self):
        with tempfile.TemporaryDirectory() as directory:
            file = Path(directory) / "records.json"
            for content in ('{"x":1,"x":2}', '{"x":NaN}', '{"x":Infinity}'):
                file.write_text(content)
                with self.assertRaises(ValueError):
                    r.read_records(file)
            file.write_bytes(b"x" * (8 * 2**20 + 1))
            with self.assertRaises(ValueError):
                r.read_records(file)
            file.write_text("{}")
            link = file.with_name("link.json")
            link.symlink_to(file)
            with self.assertRaises(ValueError):
                r.read_records(link)

    def test_physical_kv_policy_page_padding_and_first_head_rows(self):
        # These are explicit allocation-policy checks, not proof of resident fit.
        memory = self.run_for("memory")["memory"]
        bounded = {"local_storage_policy": "bounded_window", "page_tokens": 16, "layout_sha256": DIGEST}
        job = next(j for j in self.protocol["jobs"] if j["mode"] == "memory")
        r._memory(memory, job, self.protocol["resource_bounds"], bounded)
        with self.assertRaisesRegex(ValueError, "Unresolved physical"):
            r._memory(memory, job, self.protocol["resource_bounds"], {k: None for k in bounded})
        full_job = copy.deepcopy(job)
        full_job["capacity_tokens"] += 1  # forces another full page for both K/V groups
        with self.assertRaisesRegex(ValueError, "BF16 KV ledger"):
            r._memory(memory, full_job, self.protocol["resource_bounds"], self.protocol["cache_layout"])
        self.run_for("profile", "head")["profile"]["launches"][0]["m"] = 8
        with self.assertRaisesRegex(ValueError, "last-prompt-row"):
            self.check()

    def test_cli_parses_synthetic_private_record_packet_without_qualification(self):
        manifest, plan, _ = inputs(True)
        with tempfile.TemporaryDirectory() as directory:
            directory = Path(directory)
            plan_path = directory / "plan.json"
            plan_path.write_text(json.dumps(plan))
            manifest["plan_sha256"] = hashlib.sha256(plan_path.read_bytes()).hexdigest()
            manifest_path = directory / "manifest.json"
            manifest_path.write_text(json.dumps(manifest))
            # plan_sha256 is excluded from receipt scope but checked on load.
            records_path, prompts_path = directory / "records.json", directory / "prompts.json"
            records_path.write_text(json.dumps(self.records))
            prompts_path.write_text(json.dumps(self.prompts))
            process = subprocess.run([sys.executable, "-m", "megartx.prefill_runner",
                "--manifest", str(manifest_path), "--plan", str(plan_path),
                "--source-manifest", str(DOCS / "source-binding-native.json"),
                "--runner-binding", str(DOCS / "runner-binding-native.json"), "--root", str(ROOT),
                "--workload", "p2048", "--chunk", "255", "--records", str(records_path),
                "--prompts", str(prompts_path)], cwd=ROOT, capture_output=True, text=True, timeout=10)
            self.assertEqual(process.returncode, 0, process.stderr)
            result = json.loads(process.stdout)
            self.assertTrue(result["records_consistent"])
            self.assertEqual(result["provenance_kind"], "synthetic_cpu")
            self.assertFalse(result["gpu_qualified"])
            self.assertNotIn('"token_ids"', process.stdout)


if __name__ == "__main__":
    unittest.main()
